version: 2

models:
  - name: acme_semantic_view
    description: "Comprehensive ACME Services semantic view for Cortex Analyst, enabling natural language queries about technician performance, job revenue, and customer satisfaction. This semantic view combines technician performance data with job information to provide business intelligence insights."
    
    meta:
      semantic_view: true
      cortex_analyst_enabled: true
      business_domain: acme_analytics
      deployment_methods:
        - "dbt run --select acme_semantic_view (recommended)"
        - "dbt compile && snow sql -f target/compiled/..."
        - "dbt run-operation create_acme_semantic_view"
      
    # Note: Semantic views don't have traditional columns like regular tables
    # Instead, they define logical business entities (tables), relationships, facts, dimensions, and metrics

  - name: snowflake_usage_semantic_view
    description: "Comprehensive Snowflake usage analytics semantic view for the Data Engineer Assistant, combining QUERY_ATTRIBUTION_HISTORY and QUERY_HISTORY with all 85+ columns for complete query performance analysis, cost optimization, and warehouse utilization insights."
    
    meta:
      semantic_view: true
      cortex_analyst_enabled: true
      business_domain: snowflake_performance_analytics
      deployment_methods:
        - "dbt run --select snowflake_usage_semantic_view (recommended)"
        - "dbt compile && snow sql -f target/compiled/..."
      
    # Note: This semantic view provides comprehensive query performance analytics including:
    # - Query execution times, compilation times, and performance bottlenecks
    # - Warehouse utilization patterns and credit consumption analysis
    # - User and workload analysis for capacity planning
    # - Error analysis and compilation issue identification
    # - Cost analysis by warehouse, user, and query type
        
  - name: stg_parsed_documents
    description: "Parsed documents from stage for Cortex Search"
    columns:
      - name: relative_path
        description: "Path to the document in the stage"
      - name: title
        description: "Document title"
      - name: content
        description: "Full document content"
        
  - name: acme_intelligence_complete
    description: "Complete ACME Intelligence setup with all components"
    columns:
      - name: status
        description: "Setup completion status"
      - name: technician_count
        description: "Number of technicians in the system"
      - name: total_revenue_2025
        description: "Total revenue for 2025"
