# Development Environment Overrides
# Override settings for development/testing

agent:
  database: "SNOWFLAKE_INTELLIGENCE"  # Use same database as production (no separate dev db)
  
default_execution_environment:
  warehouse: "HOL_WAREHOUSE"  # Use same warehouse (no separate dev warehouse)
